@CustomerContactsModule
Feature:  Create Customer CostCentre Module

  @CustomerContactsCreateModule
  Scenario Outline: Create customer contacts with different senarios
		Given User gets the base url EndPoint and passing "<testName>" to create test
		When user pass customer number"<customerNumber>" as parameter
        Then user pass "<contactName>" and "<emailAddress>" and "<contactType>" and "<contactTitle>" and "<phoneMobile1>" and "<phoneBusiness>" and "<phoneFax>" and "<addressSt>" and "<suburbSt>" and "<postalCodeSt>" and "<addressPt>" and "<suburbPt>" and "<postalCodePt>" and "<contactOid>"as parameters
        Then user post request body to create contacts and validate with "<statusMessage>" and <statusNumber> as expected values
		Then verify the response status should be <statusCode>

    Examples:
      | testName                                                                                                                               | customerNumber   | statusCode | contactName      | emailAddress     | contactType  | contactTitle | phoneMobile1 | phoneBusiness | phoneFax | addressSt    | suburbSt  | postalCodeSt | addressPt    | suburbPt  | postalCodePt | statusMessage                                                    | statusNumber | contactOid |
      | TC-01-OLS-534-Verify user should able to create contact with all valid inputs                                                          | associatedUser   | 200        | BatJoker         | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | empty                                                            | 0            | associated |
      | TC-03-OLS-534-Verify user should not able to create contact When passing Contact Name field is Empty value                             | associatedUser   | 400        |                  | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-05-OLS-534-Verify user should not able to create contact When passing Email Address field is Empty value                            | associatedUser   | 400        | BatJoker         |                  | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-07-OLS-534-Verify user should not able to create contact When passing Mobile Phone field is Empty value                             | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       |              | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-11-OLS-534-Verify user should not able to create contact When passing contactType that doesnt allowed multiple contact              | associatedUser   | 400        | BatJoker         | update@gmail.com | associatedN  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Multiple contacts are not allowed for the selected contact type  | 42029        | associated |
      | TC-14-OLS-534-Verify user should not able to create new contact When passing Empty in street address line 1 field                      | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     |              | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-15-OLS-534- Verify user should not able to create new contact When passing Empty in suburb field                                    | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 |           | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-17-OLS-534-Verify user should not able to create new contact When passing unassociated user client state in state field             | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | state     | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated |
      | TC-18-OLS-534-Verify user should not able to create new contact When passing unassociated user client country in country field         | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | country   | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated |
      | TC-22-OLS-534-Verify user should not able to create new contact When passing invalid value in contactType                              | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | Report cont  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated |
      | TC-23-OLS-534-Verify user should not able to create new contact With invalid customer number                                           | invalidCus       | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid Customer Number                                       | 4018         | associated   |
      | TC-24-OLS-534-Verify user should not able to create new contact with unassociated customer number                                      | unAssociatedUser | 401        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | API User is unauthorized to access this customer                 | 97102        | associated |
      | TC-25-OLS-534-Verify user should not able to create new contact passing empty address line in postal address field                     | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     |              | Wellinton | 1212         |              | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-27-OLS-534-Verify user should not able to create new contact passing empty suburb in postal address                                 | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 |           | 1212         | Validation failed                                                | 12           | associated |
      | TC-28-OLS-534-Verify user should not able to create new contact passing empty postal code in postal address                            | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton |              | Validation failed                                                | 12           | associated |
      | TC-04-OLS-534-Verify user should not able to create contact When passing Contact Name field is More than 30 characters                 | associatedUser   | 400        | maxName          | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-06-OLS-534-Verify user should not able to create contact When passing Email Address field is Invalid email id                       | associatedUser   | 400        | contactUpdate_03 | invalidmail.com  | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-10-OLS-534-Verify user should not able to create contact When passing alphabets and special charaters in Mobile Phone field         | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 12345@af     | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-12-OLS-534-Verify user should not able to create contact When passing more than 15 characters in Other Phone field                  | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | maxPhone      | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-19-OLS-534-Verify user should not able to create new contact When passing invalid value in phoneFax field                           | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 1^a123   | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-21-OLS-534-Verify user should not able to create new contact When passing more than 15 characters in phoneFax field                 | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | maxPhone | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |
      | TC-31-OLS-534-Verify user should not able to create new contact When passing more than 15 characters in postalcode field               | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | maxPhone     | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated |

#Need to check

#      | TC-08-OLS-534-Verify user should not able to create contact When passing Mobile Phone field is less than 4 characters                  | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 123          | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone mobile 1 does not meet the expected length             | 42011        | associated |
#      | TC-09-OLS-534-Verify user should not able to create Contact When passing Mobile Phone field is more than 15 characters                 | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | maxPhone     | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone mobile 1 does not meet the expected length             | 42011        | associated |
#      | TC-13-OLS-534-Verify user should not able to create contact When passing less than 4 characters in Other Phone field                   | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 12            | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone business does not meet the expected length             | 42013        | associated |
#      | TC-16-OLS-534-Verify user should not able to create new contact When passing less than 3 characters in suburb field                    | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | We        | 1212         | YYY Box 5233 | Wellinton | 1212         | The street address suburb does not meet the expected length      | 42019        | associated |
#      | TC-20-OLS-534-Verify user should not able to create new contact When passing less than 4 characters in phoneFax field                  | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 41       | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone fax does not meet the expected length                  | 42015        | associated |
#      | TC-26-OLS-534-Verify user should not able to create new contact passing less than 2 characters in address line field in postal address | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YY           | Wellinton | 1212         | The postal address line does not meet the expected length        | 42022        | associated |
#      | TC-29-OLS-534-Verify user should able to create contact When passing unassociated contactType                                          | associatedUser   | 400        | BatJoker         | update@gmail.com | unAssociated | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated |
#      | TC-30-OLS-534-Verify user should not able to create new contact When passing less than 4 characters in postalcode field                | associatedUser   | 400        | contactUpdate_03 | update@gmail.com | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 12           | YYY Box 5233 | Wellinton | 1212         | The street address postal code does not meet the expected length | 42020        | associated |


  @CustomerContactsUpdatesModule
  Scenario Outline: Update customer contacts with different senarios
    Given User gets the base url EndPoint and passing "<testName>" to create test
    When user pass customer number"<customerNumber>" as parameter
    Then user pass "<contactName>" and "<emailAddress>" and "<contactType>" and "<contactTitle>" and "<phoneMobile1>" and "<phoneBusiness>" and "<phoneFax>" and "<addressSt>" and "<suburbSt>" and "<postalCodeSt>" and "<addressPt>" and "<suburbPt>" and "<postalCodePt>" and "<contactOid>"as parameters
    Then user put request body to create contacts and validate with "<statusMessage>" and <statusNumber> as expected values
    Then verify the response status should be <statusCode>

    Examples:
      | testName                                                                                                                                 | customerNumber   | statusCode | contactName      | emailAddress      | contactType  | contactTitle | phoneMobile1 | phoneBusiness | phoneFax | addressSt    | suburbSt  | postalCodeSt | addressPt    | suburbPt  | postalCodePt | statusMessage                                                    | statusNumber | contactOid   |
      | TC-01-OLS-537-Verify user should able to update a contact with all valid inputs                                                          | associatedUser   | 200        | BatJoker         | update1@gmail.com | associatedY  | 1231ABC      | 13132        | 13132         | 4141     | YYY Box 5233 | Gotham    | 1212         | YYY Box 5233 | Gotham    | 1212         | empty                                                            | 0            | associated   |
      | TC-03-OLS-537-Verify user should not able to update a contact When passing Contact Name field is Empty value                             | associatedUser   | 400        |                  | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-05-OLS-537-Verify user should not able to update a contact When passing Email Address field is Empty value                            | associatedUser   | 400        | violet2          |                   | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-07-OLS-537-Verify user should not able to update a contact When passing Mobile Phone field is Empty value                             | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       |              | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-11-OLS-537-Verify user should not able to update a contact When passing contactType that doesnt allowed multiple contact              | associatedUser   | 400        | violet22         | update@gmail.com  | associatedN  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Multiple contacts are not allowed for the selected contact type  | 42029        | associated   |
      | TC-14-OLS-537-Verify user should not able to update a new contact When passing Empty in street address line 1 field                      | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     |              | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-15-OLS-537- Verify user should not able to update a new contact When passing Empty in suburb field                                    | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 |           | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-17-OLS-537-Verify user should not able to update a new contact When passing unassociated user client state in state field             | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | state     | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated   |
      | TC-18-OLS-537-Verify user should not able to update a new contact When passing unassociated user client country in country field         | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | country   | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated   |
      | TC-22-OLS-537-Verify user should not able to update a new contact When passing invalid value in contactType                              | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | Report cont  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated   |
      | TC-23-OLS-537-Verify user should not able to update a new contact With invalid customer number                                           | invalidCus       | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid Customer Number                                       | 4018         | associated   |
      | TC-24-OLS-537-Verify user should not able to update a new contact with unassociated customer number                                      | unAssociatedUser | 401        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | API User is unauthorized to access this customer                 | 97102        | associated   |
      | TC-25-OLS-537-Verify user should not able to update a new contact passing empty address line in postal address field                     | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     |              | Wellinton | 1212         |              | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-27-OLS-537-Verify user should not able to update a new contact passing empty suburb in postal address                                 | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 |           | 1212         | Validation failed                                                | 12           | associated   |
      | TC-28-OLS-537-Verify user should not able to update a new contact passing empty postal code in postal address                            | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton |              | Validation failed                                                | 12           | associated   |
      | TC-30-OLS-537-Verify user should not able to update a contact not present in specified customer                                          | associatedUser   | 400        | BatJoker         | update@gmail.com  | associatedY  | 123ABC       | 919191       | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Contact not found                                               | 42034        | unAssociated |
      | TC-02-OLS-537-Verify user should not able to update a contact When passing Contact Name field is Less than 3 characters                  | associatedUser   | 400        | vi               | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-04-OLS-537-Verify user should not able to update a contact When passing Contact Name field is More than 30 characters                 | associatedUser   | 400        | maxName          | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-06-OLS-537-Verify user should not able to update a contact When passing Email Address field is Invalid email id                       | associatedUser   | 400        | contactUpdate_03 | invalidmail.com   | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-10-OLS-537-Verify user should not able to update a contact When passing alphabets and special charaters in Mobile Phone field         | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 12345@af     | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-12-OLS-537-Verify user should not able to update a contact When passing more than 15 characters in Other Phone field                  | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | maxPhone      | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-19-OLS-537-Verify user should not able to update a new contact When passing invalid value in phoneFax field                           | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 1^a123   | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-21-OLS-537-Verify user should not able to update a new contact When passing more than 15 characters in phoneFax field                 | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | maxPhone | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |
      | TC-32-OLS-537-Verify user should not able to update a new contact When passing more than 15 characters in postalcode field               | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | maxPhone     | YYY Box 5233 | Wellinton | 1212         | Validation failed                                                | 12           | associated   |

#Need to check
#      | TC-08-OLS-537-Verify user should not able to update a contact When passing Mobile Phone field is less than 4 characters                  | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 123          | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone mobile 1 does not meet the expected length             | 42011        | associated   |
#      | TC-09-OLS-537-Verify user should not able to update a Contact When passing Mobile Phone field is more than 15 characters                 | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | maxPhone     | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone mobile 1 does not meet the expected length             | 42011        | associated   |
#      | TC-13-OLS-537-Verify user should not able to update a contact When passing less than 4 characters in Other Phone field                   | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 12            | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone business does not meet the expected length             | 42013        | associated   |
#      | TC-16-OLS-537-Verify user should not able to update a new contact When passing less than 3 characters in suburb field                    | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | We        | 1212         | YYY Box 5233 | Wellinton | 1212         | The street address suburb does not meet the expected length      | 42019        | associated   |
#      | TC-20-OLS-537-Verify user should not able to update a new contact When passing less than 4 characters in phoneFax field                  | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 41       | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | The phone fax does not meet the expected length                  | 42015        | associated   |
#      | TC-26-OLS-537-Verify user should not able to update a new contact passing less than 2 characters in address line field in postal address | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YY           | Wellinton | 1212         | The postal address line does not meet the expected length        | 42022        | associated   |
#      | TC-29-OLS-537-Verify user should able to update a contact When passing unassociated contactType                                          | associatedUser   | 400        | violet22         | update@gmail.com  | unAssociated | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid entry                                                    | 6            | associated   |
#      | TC-31-OLS-537-Verify user should not able to update a new contact When passing less than 4 characters in postalcode field                | associatedUser   | 400        | contactUpdate_03 | update@gmail.com  | associatedY  | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 12           | YYY Box 5233 | Wellinton | 1212         | The street address postal code does not meet the expected length | 42020        | associated   |


  @OLSGetCustomerContactDetails
  Scenario Outline: Get customer contacts with different senarios(Both postive and negative scenarios)
    Given User gets the base url EndPoint and passing "<testName>" to create test
    When user pass customer number"<customerNumber>" as parameter
    Then user hit the get request to get the list of customer contact details and validate with "<statusMessage>" and <statusNumber> as expected values
    Then verify the response status should be <statusCode>

    Examples:
      | testName                                                                                              | customerNumber   | statusCode | statusMessage                                    | statusNumber |
      | TC-01-OLS-531-Verify user should able to get customer contact details with expected fields and values | associatedUser   | 200        | empty                                            | 0            |
      | TC-02-OLS-531-Validate the expected error message for invalid account number                          | invalidCus       | 400        | Invalid Customer Number                          | 4018         |
      | TC-03-OLS-531-Validate the expected error message for passing unassociated account number             | unAssociatedUser | 401        | API User is unauthorized to access this customer | 97102        |

  @OLSDeleteCustomerContactDetails
  Scenario Outline: Get customer contacts with different senarios(Both postive and negative scenarios)
    Given User gets the base url EndPoint and passing "<testName>" to create test
    When user pass customer number"<customerNumber>" as parameter
    Then user pass "<contactName>" and "<emailAddress>" and "<contactType>" and "<contactTitle>" and "<phoneMobile1>" and "<phoneBusiness>" and "<phoneFax>" and "<addressSt>" and "<suburbSt>" and "<postalCodeSt>" and "<addressPt>" and "<suburbPt>" and "<postalCodePt>" and "<contactOid>"as parameters
    Then user hit delete request body to delete a contact and validate with "<statusMessage>" and <statusNumber> as expected values
    Then verify the response status should be <statusCode>

    Examples:
      | testName                                                                                                                | customerNumber   | statusCode | contactName      | emailAddress     | contactType | contactTitle | phoneMobile1 | phoneBusiness | phoneFax | addressSt    | suburbSt  | postalCodeSt | addressPt    | suburbPt  | postalCodePt | statusMessage                                                 | statusNumber | contactOid   |
      | TC-01-OLS-649-Verify user should able to delete a customer contact details with expected fields and values              | associatedUser   | 200        | violet22         | update@gmail.com | associatedY | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | empty                                                         | 0            | associated   |
      | TC-02-OLS-649-Verify user should not able to delete a contact not present in specified customer                         | associatedUser   | 400        | violet22         | update@gmail.com | associatedY | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Contact not found                                             | 42034        | unAssociated |
      | TC-03-OLS-649-Verify user should not able to delete a new contact With invalid customer number                          | invalidCus       | 400        | contactUpdate_03 | update@gmail.com | associatedY | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | Invalid Customer Number                                       | 4018         | associated   |
      | TC-04-OLS-649-Verify user should not able to delete a new contact with unassociated customer number                     | unAssociatedUser | 401        | contactUpdate_03 | update@gmail.com | associatedY | 123ABC       | 919191919191 | 919191        | 4141     | YYY Box 5233 | Wellinton | 1212         | YYY Box 5233 | Wellinton | 1212         | API User is unauthorized to access this customer              | 97102        | associated   |